title: Netrunner Codex
description: TBC
theme: just-the-docs

url: https://netrunnercodex.github.io

permalink: pretty

logo: "/assets/images/netrunner-codex200.png"
favicon_ico: "/assets/images/favicon.ico"

color_scheme: foo

nav_enabled: true

aux_links:
  Github: https://github.com/NetrunnerCodex/NetrunnerCodex.github.io

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: purple
  new:
    title: New
    color: green
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red

back_to_top: true
back_to_top_text: "Back to top"
